### ISSUE TITLE
Missing __init__.py in lib dir

### ISSUE THREAD

**Issue by jhagberg** [brunetton/redminetimesync#10]
Running redminetimesync gives me erro
./redminetimesync.py 15-02-09
Traceback (most recent call last):
  File "./redminetimesync.py", line 28, in <module>
    from lib import common
ImportError: No module named lib

Adding the file `__init__.py` in the lib dir solves this
cd lib
touch `__init__.py` 

./redminetimesync.py 15-02-09
Sync tasks for 15-02-09 ?

Press ENTER to validate ..

**Comment by brunetton** [comment]
Interesting.
What version of Python do you use ?

**Comment by jhagberg** [comment]
Python 2.7.6
Linux  3.13.0-24-generic #47-Ubuntu SMP Fri May 2 23:30:00 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
