### ISSUE TITLE
ImportError: No module named yaml

### ISSUE THREAD

**Issue by jhagberg** [brunetton/redminetimesync#9]
Hej

Trying to run redminetimesync.py 

I then get ImportError: No module named yaml 

It looks like this dependency is missing in the readme.

**Comment by jhagberg** [comment]
apt-get install  python-yaml 
fixes this
Same with python-docopt 

and then pip install python-redmine moment

Maybe just ad it to the readme?

**Comment by brunetton** [comment]
Indeed. Thanks for your request. 
For the moment I didn't added Python dependant modules in readme. I'll add it.
